name: CICD

on:
  push:
    branches:
      - "master"

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}/test-push-example

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD |
          && echo "Login done"
      # - name: Build docker image
      #   run: docker build -t $DOCKER_REPOSITORY .
      # - name: Push image to Docker Hub
      #   run: docker push $DOCKER_REPOSITORY \
      #     && echo "Done""

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Run jobs Deploy"